# Generated by Django 5.1.3 on 2024-11-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_comment_id_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
